[[pligins]]
repo = 'Shougo/dein.vim'

# =============================================
# colorscheme
# =============================================

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
source ~/.config/nvim/plugins/vim-colorschemes.rc.vim
'''

# =============================================
# status bar
# =============================================

