[[pligins]]
repo = 'Shougo/dein.vim'

# =============================================
# colorscheme
# =============================================

[[plugins]]
repo = 'flazz/vim-colorschemes'
hook_add = '''
source ~/.config/nvim/plugins/vim-colorschemes.rc.vim
'''

# =============================================
# status bar
# =============================================

#[[plugins]]
#repo = 'itchyny/lightline.vim'
#hook_add = '''
#source ~/.config/nvim/plugins/lightline.rc.vim
#'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
'''

# =============================================
# git
# =============================================

[[plugins]]
repo = 'tpope/vim-fugitive'

# =============================================
# quickrun
# =============================================

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.rc.vim
'''

# =============================================
# bracket
# =============================================

[[plugins]]
repo = 'cohama/lexima.vim'

# =============================================
# filer
# =============================================

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']
