# ============================================================ 
# plugin manager
# ============================================================ 

[[plugins]]
repo = 'Shougo/dein.vim'

# ============================================================ 
# colorscheme
# ============================================================ 

[[plugins]]
repo = 'flazz/vim-colorschemes'

# ============================================================ 
# statusline
# ============================================================ 

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

# ============================================================ 
# git
# ============================================================ 

[[plugins]]
repo = 'tpope/vim-fugitive'

# ============================================================ 
# denite.nvim
# ============================================================ 

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''
