# ============================================================ 
# plugin manager
# ============================================================ 

[[plugins]]
repo = 'Shougo/dein.vim'

# ============================================================ 
# colorscheme
# ============================================================ 
[[plugins]]

# ============================================================ 
# statusline
# ============================================================ 

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.rc.vim
'''

# ============================================================ 
# git
# ============================================================ 

[[plugins]]
repo = 'tpope/vim-fugitive'
